### ISSUE TITLE
npm start ERROR , can't run and see the performance

### ISSUE THREAD

**Issue by mengxiw** [altab-ch/Angular2-Parse#1]
Following the steps, after run 'npm install' and 'std install'. 
This is the error after the command "npm start":

> angular2-authentication-sample@0.0.0 start C:\Users\Administrator.XZ-20140618R
> VRF\app\Angular2-Parse-master
> webpack-dev-server --inline -d --colors --display-error-details --display-cach
> ed --host 192.168.0.10 --port 3005

events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 192.168.0.10:3005
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at Server._listen2 (net.js:1225:19)
    at listen (net.js:1274:10)
    at net.js:1383:9
    at nextTickCallbackWith3Args (node.js:466:9)
    at process._tickCallback (node.js:372:17)
    at Function.Module.runMain (module.js:433:11)
    at startup (node.js:141:18)
    at node.js:977:3

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\
node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! angular2-authentication-sample@0.0.0 start: `webpack-dev-server --inlin
e -d --colors --display-error-details --display-cached --host 192.168.0.10 --por
t 3005`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-authentication-sample@0.0.0 start script 'webpac
k-dev-server --inline -d --colors --display-error-details --display-cached --hos
t 192.168.0.10 --port 3005'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-authenticati
on-sample package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline -d --colors --display-error-details --d
isplay-cached --host 192.168.0.10 --port 3005
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular2-authentication-sample
npm ERR! There is likely additional logging output above.

I didn't see these error before.
I tried change the port and run, the error still there.
I also tried "npm update -g", "npm cache clean" but nothing change.
I try to install gulp to run the serve, but it still has errors.

**Comment by ghost** [comment]
+1
same error for me
but tsd install also fails (running on Mac OSX el capitan)

**Comment by cokearns** [comment]
+1
same errors as happschinson

**Comment by devrockzz** [comment]
+1
same error , please update this

**Comment by alexrmacleod** [comment]
Please update, so many people use parse and want to make web apps! this would be a awesome place to start!

**Comment by Amolmore456** [comment]
Fix It Man

**Comment by valero90** [comment]
You gotta change line 7 of package.json: 
"start": "webpack-dev-server --inline -d --colors --display-error-details --display-cached --host **192.168.0.10** --port 3000",

With this: 
"start": "webpack-dev-server --inline -d --colors --display-error-details --display-cached --host **0.0.0.0** --port 3000",

But now that I've changed it I have another error and can't run the app: 
chunk    {2} app.js, app.js.map (app) 40 bytes {1} [rendered]
    [0] multi app 40 bytes {2} [built] [1 error]

ERROR in ./src/index.ts
Module build failed: TypeError: TS.parseConfigFile is not a function
    at readConfig (/Users/valero90/Sites/Angular2-Parse/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:51:15)
    at createInstance (/Users/valero90/Sites/Angular2-Parse/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:62:18)
    at getLoaderInstance (/Users/valero90/Sites/Angular2-Parse/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:163:20)
    at Object.loader (/Users/valero90/Sites/Angular2-Parse/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:12:14)
 @ multi app

ERROR in ./src/common/BrowserDomAdapter.ts
Module build failed: TypeError: TS.parseConfigFile is not a function
    at readConfig (/Users/valero90/Sites/Angular2-Parse/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:51:15)
    at createInstance (/Users/valero90/Sites/Angular2-Parse/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:62:18)
    at getLoaderInstance (/Users/valero90/Sites/Angular2-Parse/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:163:20)
    at Object.loader (/Users/valero90/Sites/Angular2-Parse/node_modules/typescript-simple-loader/dist/typescript-simple-loader.js:12:14)
 @ multi angular2
webpack: Failed to compile.

Please help us so we can use this app which in my case, can help me a lot!
